# cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_AR_REPO_PATH}/${_IMAGE_NAME}:${SHORT_SHA}'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - '${_AR_REPO_PATH}/${_IMAGE_NAME}:${SHORT_SHA}'
    - '${_AR_REPO_PATH}/${_IMAGE_NAME}:latest'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_AR_REPO_PATH}/${_IMAGE_NAME}:latest'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_AR_REPO_PATH}/${_IMAGE_NAME}:${SHORT_SHA}'

substitutions:
  _GCP_PROJECT_ID: 'hogeticlab-legs-prd'
  _GCP_REGION: 'asia-northeast1'
  _AR_REPO: 'ip-name-url'

  _IMAGE_NAME: 'pixiv-ip'
  _AR_REPO_PATH: '${_GCP_REGION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_AR_REPO}'

images:
  - '${_AR_REPO_PATH}/${_IMAGE_NAME}:latest'
  - '${_AR_REPO_PATH}/${_IMAGE_NAME}:${SHORT_SHA}'
