# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pixiv-scraper-job-${session_uuid}-${batch_index}
  namespace: collectro 
spec:
  # 失敗した場合にリトライしない設定
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: collectro
      containers:
      - name: pixiv-scraper
        image: "asia-northeast1-docker.pkg.dev/hogeticlab-legs-prd/ip-name-url/pixiv-scraper:latest"
        command:
          - "python"
          - "unified_pixiv_search.py"
        env:
          - name: GCP_PROJECT_ID
            value: "${GCP_PROJECT_ID}"
          - name: BIGQUERY_DATASET
            value: "${BIGQUERY_DATASET}"
          - name: WRITE_MODE
            value: "WRITE_TRUNCATE"
      restartPolicy: Never